# Build Settings
gems:
  - jekyll-paginate
#Site settings
title: "waCa"
description: "블로그"
email: "waca5436@gmail.com"

#blog setting
blogTitle: "이것저것"

paginate: 5

#author
author: "waca"
authorImg: "/images/2_twitter.JPG"

#social
twitter: "waca08_18"
facebook: "tk5436"
github: "KOR-waca"