# Build Settings
gems: [jekyll-paginate, jekyll-paginate-category]
#Site settings
title: "waCa"
description: "블로그"
email: "waca5436@gmail.com"

#blog setting
blogTitle: "이것저것"

paginate: 5
paginate_path: "page:num"

category_dir: "blog"
category_layout: "index.html"

#author
author: "waca"
authorImg: "/images/2_twitter.JPG"

#social
twitter: "waca08_18"
facebook: "tk5436"
github: "KOR-waca"