# Build Settings
gems:
  - jekyll-paginate
  - jekyll-paginate-category
  - jemoji
  - jekyll-feed

#Site settings
title: "waCa"
description: "블로그"
email: "waca.chong.dev@gmail.com"

#blog setting
future: true
blogTitle: "이것저것"
url: "https://blog.wacav.com/"


#disqus Shorname
disqus: korwacagithubio

#paging
paginate: 5
paginate_path: "/page:num"

#author
author: "waca"
authorImg: "/images/2_twitter.JPG"

#social
twitter: "waca08_18"
twitter_url: "https://twitter.com/waca08_18"
facebook: "tk5436"
facebook_url: "https://facebook.com/tk5436"
github: "wacav"
github_url: "https://github.com/wacav"
resume: "waCa"
resume_url: "https://www.cakeresume.com/waca"



#RSS
