name: Herring Cove
author: Herring Cove
baseurl: /
description: theme for jekyll
github: http://github.com/kor-waca
twitter: http://www.twitter.com/waca08_18
facebook: http://www.facebook.com/tk5436
email: waca5436@gmail.com
disqus: waca

##Make sure to edit the above fields, especially for disqus.

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
